# application-local.yml
spring:
  # 解决数据库连接问题
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3307/webcollector?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:webcollector}
    password: ${DB_PASSWORD:webcollector_dev}

    # 解决数据库连接的复用和限流问题
    hikari:
      # 防止高并发瞬间把数据库连接打满
      maximum-pool-size: 10
      # 减少频繁创建连接的开销
      minimum-idle: 2
      # 如果当前 10 个连接都在忙，新的业务线程最多等待 3000 毫秒获取连接；超时后抛异常
      connection-timeout: 3000

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD:webcollector_dev}
      timeout: 3000ms

  # 解决数据库结构演进问题
  flyway:
    enabled: true
    locations: classpath:db/migration

# 解决 Java 与数据库命名差异
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true